name: Daily Ryanair Scraper

on:
  schedule:
    - cron: '0 7 * * *'  # kasdien 07:00 UTC
  workflow_dispatch:     # leidžia paleisti rankiniu būdu

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas playwright
          playwright install chromium

      - name: Run scraper
        run: python scraper/ryanair_scraper.py

      - name: Commit CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/flights.csv
          git commit -m "Daily flight data update" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload debug screenshot (optional)
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: screenshot.png
          if-no-files-found: ignore
