name: Daily Ryanair Scraper

on:
  schedule:
    - cron: "0 7 * * *"       # kasdien 07:00 UTC
  workflow_dispatch:

permissions:
  contents: write              # leidžia push’ą

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python & deps
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Install Playwright browsers
        run: python -m playwright install --with-deps chromium

      - name: Run scraper
        run: python scraper/ryanair_scraper.py

      - name: Commit CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/flights.csv
          git commit -m "Daily Ryanair price update" || echo "no changes"
          git push

      - name: Upload debug screenshot (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: flights_csv
          path: data/flights.csv
